# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a91369c93a410ef8e026417b4b1c1f7a0f3e5fe02a930032ede6787173fc26300c26764efc7a4a1326560162197fe9893223e018c5d1586340ae279611226db

test:
  secret_key_base: bbeade3f4ef3a2eec3a95b28bed33344670b4bbb90d1d876e37784bcec658bd3d515ac70f9c473fd520f47dd6bedd959d9b332e08adee72dd1288a6b440cd945

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
